# Run DB migrations before these requests

# testing the API end-to-end

### Health check
GET http://localhost:8080/healthcheck


### Register a new user
POST http://localhost:8080/api/v1/register
Accept: application/json
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "valid@email.com",
  "password": "password"
}


### Login
POST http://localhost:8080/api/v1/login
Accept: application/json
Content-Type: application/json

{
  "email": "valid@email.com",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}


### Create address
POST http://localhost:8080/api/v1/address
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "isDefault": true,
  "line1": "123 Main St",
  "city": "London",
  "country": "UK",
  "postcode": "AB12 3CD"
}


### Get addresses for user
GET http://localhost:8080/api/v1/address
Accept: application/json
Authorization: {{auth_token}}


### Get default address for user
GET http://localhost:8080/api/v1/address?default=true
Accept: application/json
Authorization: {{auth_token}}


### Get products
GET http://localhost:8080/api/v1/products
Accept: application/json
Authorization: {{auth_token}}


### Checkout cart
POST http://localhost:8080/api/v1/cart/checkout
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "items": [
    {
      "productID": 1,
      "quantity": 2
    },
    {
      "productID": 2,
      "quantity": 3
    }
  ]
}
